// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdblhQoyI_dV8oKPgDVKAyKw4S1TNy4o',
    appId: '1:292469092681:web:1812cbb5b8facabc772a98',
    messagingSenderId: '292469092681',
    projectId: 'inventur-9779b',
    authDomain: 'inventur-9779b.firebaseapp.com',
    storageBucket: 'inventur-9779b.appspot.com',
    measurementId: 'G-7KR5921QE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyRYS3PTH1RMec8RZvayBYsTbqCutrKO8',
    appId: '1:292469092681:android:bf04bf8c3eab116f772a98',
    messagingSenderId: '292469092681',
    projectId: 'inventur-9779b',
    storageBucket: 'inventur-9779b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86p2zgomkD_zJLfJaqa8nyUjYOCMg2JU',
    appId: '1:292469092681:ios:bc2cebf106e29a5c772a98',
    messagingSenderId: '292469092681',
    projectId: 'inventur-9779b',
    storageBucket: 'inventur-9779b.appspot.com',
    iosBundleId: 'com.example.lojatecharchitectures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB86p2zgomkD_zJLfJaqa8nyUjYOCMg2JU',
    appId: '1:292469092681:ios:037762bf9209ecd3772a98',
    messagingSenderId: '292469092681',
    projectId: 'inventur-9779b',
    storageBucket: 'inventur-9779b.appspot.com',
    iosBundleId: 'com.example.lojatecharchitectures.RunnerTests',
  );
}
